#include <iostream>
#include <conio.h>
#include <stdio>
#include <stdlib>

void main(){
char a0[10],a1[10],a2[10],a3[10],a4[10],a5[10],a6[10],a7[10],a8[10],a9[10];
int x0,x1,x2,x3,x4,x5,x6,x7,x8,x9;
int condicion0,condicion1,condicion2,condicion3,condicion4,condicion5,condicion6,
condicion7,condicion8,condicion9;

cout<<"Ingrese el token: \n";
cin>>a0;
cout<<"Ingrese el codigo: \n";
cin>>x0;
cout<<"Digite el numero para la siguiente accion a realizar \n";
cout<<"1. Agregar otro token   2. Generar tabla \n";
cin>>condicion0;

if (condicion0==1){
cout<<"Ingrese el token: \n";
cin>>a1;
cout<<"Ingrese el codigo: \n";
cin>>x1;
cout<<"Digite el numero para la siguiente accion a realizar \n";
cout<<"1. Agregar otro token   2. Generar tabla \n";
cin>>condicion1;
		if (condicion1==1){
      cout<<"Ingrese el token: \n";
		cin>>a1;
		cout<<"Ingrese el codigo: \n";
		cin>>x1;
		cout<<"Digite el numero para la siguiente accion a realizar \n";
		cout<<"1. Agregar otro token   2. Generar tabla \n";
		cin>>condicion2;
      	if (condicion2==1){
      	cout<<"Ingrese el token: \n";
			cin>>a2;
			cout<<"Ingrese el codigo: \n";
			cin>>x2;
			cout<<"Digite el numero para la siguiente accion a realizar \n";
			cout<<"1. Agregar otro token   2. Generar tabla \n";
			cin>>condicion3;

         if (condicion3==1){
			cout<<"Ingrese el token: \n";
			cin>>a3;
			cout<<"Ingrese el codigo: \n";
			cin>>x3;
         cout<<"Digite el numero para la siguiente accion a realizar \n";
			cout<<"1. Agregar otro token   2. Generar tabla \n";
			cin>>condicion4;
			if (condicion4==1){
      	cout<<"Ingrese el token: \n";
			cin>>a4;
			cout<<"Ingrese el codigo: \n";
			cin>>x4;
			cout<<"Digite el numero para la siguiente accion a realizar \n";
			cout<<"1. Agregar otro token   2. Generar tabla \n";
			cin>>condicion5;
      	if (condicion5==1){
      	cout<<"Ingrese el token: \n";
			cin>>a5;
			cout<<"Ingrese el codigo: \n";
			cin>>x5;
			cout<<"Digite el numero para la siguiente accion a realizar \n";
			cout<<"1. Agregar otro token   2. Generar tabla \n";
			cin>>condicion6;
         if (condicion6==1){
			cout<<"Ingrese el token: \n";
			cin>>a6;
			cout<<"Ingrese el codigo: \n";
			cin>>x6;
         cout<<"Digite el numero para la siguiente accion a realizar \n";
			cout<<"1. Agregar otro token   2. Generar tabla \n";
			cin>>condicion7;
			if (condicion7==1){
      	cout<<"Ingrese el token: \n";
			cin>>a7;
			cout<<"Ingrese el codigo: \n";
			cin>>x7;
			cout<<"Digite el numero para la siguiente accion a realizar \n";
			cout<<"1. Agregar otro token   2. Generar tabla \n";
			cin>>condicion8;
      	if (condicion8==1){
      	cout<<"Ingrese el token: \n";
			cin>>a8;
			cout<<"Ingrese el codigo: \n";
			cin>>x8;
			cout<<"Digite el numero para la siguiente accion a realizar \n";
			cout<<"1. Agregar otro token   2. Generar tabla \n";
			cin>>condicion9;
      	if (condicion9==1){
      	cout<<"Ingrese el token: \n";
			cin>>a9;
			cout<<"Ingrese el codigo: \n";
			cin>>x9;
			cout<<"El programa cuenta con una limitacion de datos \n";
			cout<<"Tabla final de datos \n";
cout<<"  Codigo        Token \n";
cout<<"     "<<x0<<"          "<<a0<<endl;
cout<<"     "<<x1<<"          "<<a1<<endl;
cout<<"     "<<x2<<"          "<<a2<<endl;
cout<<"     "<<x3<<"          "<<a3<<endl;
cout<<"     "<<x4<<"          "<<a4<<endl;
cout<<"     "<<x5<<"          "<<a5<<endl;
cout<<"     "<<x6<<"          "<<a6<<endl;
cout<<"     "<<x7<<"          "<<a7<<endl;
cout<<"     "<<x8<<"          "<<a8<<endl;
cout<<"     "<<x9<<"          "<<a9<<endl;
      }
      else if(condicion9==2){
cout<<"  Codigo        Token \n";
cout<<"     "<<x0<<"          "<<a0<<endl;
cout<<"     "<<x1<<"          "<<a1<<endl;
cout<<"     "<<x2<<"          "<<a2<<endl;
cout<<"     "<<x3<<"          "<<a3<<endl;
cout<<"     "<<x4<<"          "<<a4<<endl;
cout<<"     "<<x5<<"          "<<a5<<endl;
cout<<"     "<<x6<<"          "<<a6<<endl;
cout<<"     "<<x7<<"          "<<a7<<endl;
cout<<"     "<<x8<<"          "<<a8<<endl;
cout<<"     "<<x9<<"          "<<a9<<endl;
      }
      }
      else if(condicion8==2){
cout<<"  Codigo        Token \n";
cout<<"     "<<x0<<"          "<<a0<<endl;
cout<<"     "<<x1<<"          "<<a1<<endl;
cout<<"     "<<x2<<"          "<<a2<<endl;
cout<<"     "<<x3<<"          "<<a3<<endl;
cout<<"     "<<x4<<"          "<<a4<<endl;
cout<<"     "<<x5<<"          "<<a5<<endl;
cout<<"     "<<x6<<"          "<<a6<<endl;
cout<<"     "<<x7<<"          "<<a7<<endl;
cout<<"     "<<x8<<"          "<<a8<<endl;
      }
      }
      else if(condicion7==2){
cout<<"  Codigo        Token \n";
cout<<"     "<<x0<<"          "<<a0<<endl;
cout<<"     "<<x1<<"          "<<a1<<endl;
cout<<"     "<<x2<<"          "<<a2<<endl;
cout<<"     "<<x3<<"          "<<a3<<endl;
cout<<"     "<<x4<<"          "<<a4<<endl;
cout<<"     "<<x5<<"          "<<a5<<endl;
cout<<"     "<<x6<<"          "<<a6<<endl;
cout<<"     "<<x7<<"          "<<a7<<endl;


      }
}
else if(condicion6==2){
cout<<"  Codigo        Token \n";
cout<<"     "<<x0<<"          "<<a0<<endl;
cout<<"     "<<x1<<"          "<<a1<<endl;
cout<<"     "<<x2<<"          "<<a2<<endl;
cout<<"     "<<x3<<"          "<<a3<<endl;
cout<<"     "<<x4<<"          "<<a4<<endl;
cout<<"     "<<x5<<"          "<<a5<<endl;
cout<<"     "<<x6<<"          "<<a6<<endl;

      }
      }
      else if(condicion5==2){
cout<<"  Codigo        Token \n";
cout<<"     "<<x0<<"          "<<a0<<endl;
cout<<"     "<<x1<<"          "<<a1<<endl;
cout<<"     "<<x2<<"          "<<a2<<endl;
cout<<"     "<<x3<<"          "<<a3<<endl;
cout<<"     "<<x4<<"          "<<a4<<endl;
cout<<"     "<<x5<<"          "<<a5<<endl;
      }
      }
      else if(condicion4==2){
cout<<"  Codigo        Token \n";
cout<<"     "<<x0<<"          "<<a0<<endl;
cout<<"     "<<x1<<"          "<<a1<<endl;
cout<<"     "<<x2<<"          "<<a2<<endl;
cout<<"     "<<x3<<"          "<<a3<<endl;
cout<<"     "<<x4<<"          "<<a4<<endl;
      }
}
else if(condicion3==2){
cout<<"  Codigo        Token \n";
cout<<"     "<<x0<<"          "<<a0<<endl;
cout<<"     "<<x1<<"          "<<a1<<endl;
cout<<"     "<<x2<<"          "<<a2<<endl;
cout<<"     "<<x3<<"          "<<a3<<endl;

}

      }
      else if(condicion2==2){
cout<<"  Codigo        Token \n";
cout<<"     "<<x0<<"          "<<a0<<endl;
cout<<"     "<<x1<<"          "<<a1<<endl;
cout<<"     "<<x2<<"          "<<a2<<endl;
      }

      }
      else if
      (condicion1==2){
cout<<"  Codigo        Token \n";
cout<<"     "<<x0<<"          "<<a0<<endl;
cout<<"     "<<x1<<"          "<<a1<<endl;
      }
}
else if(condicion0==2){
cout<<"  Codigo        Token \n";
cout<<"     "<<x0<<"          "<<a0<<endl;

}



getch();
}
